
//this file was autogenerated by dynamically running set-env.ts and using dotenv for managing API key secrecy
export const Environment = {
    production: true,
    featureFlags: {
        enableFollowFeature: true
    },
    mapbox: {
        accessToken: 'pk.eyJ1IjoiYWFkYW1lIiwiYSI6ImNrZ2NjZDJyaDA4NjQzMHFvZThwcWRkNWEifQ.bTttOdTmGs77MDHsIn3xow'
    }
};
