
//this file was autogenerated by dynamically running set-env.ts and using dotenv for managing API key secrecy
export module Environment {
    export const production = false;
    export const featureFlags = {
        enableFollowFeature: true
    }
    export const mapbox = {
        accessToken: 'pk.eyJ1IjoiYWFkYW1lIiwiYSI6ImNrZ2NjZDJyaDA4NjQzMHFvZThwcWRkNWEifQ.bTttOdTmGs77MDHsIn3xow'
    }
}
